require: 'rubocop-rspec'
AllCops:
  Exclude:
    - 'bin/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
Rails:
  Enabled: true
Documentation:
  Enabled: false