# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276e8c1a3a71da1e8eee057732b633160dedfa94c22454168a3e52d2faad8cdfdd77c345203afc099b1f46b772a01fb49744477632e7edfd6797a215b6f5fb7d

test:
  secret_key_base: 29283e5653e5bf096c78da690bccc063f46742cbbb3bf585d6b932043eb4d504a6eb1618a47401d461b1115978e70105265fd041933c81ea1cf51c083b5534e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
